<?php
$activities = array(
    "Agriculture",
    "Mode, industrie textile",
    "Industrie alimentaire",
    "Chimie, pharmacie",
    "Audiovisuel - Spectacle",
    "Social",
    "Énergie",
    "Construction aéronautique, ferroviaire et navale",
    "Banque, assurance",
    "Maintenance, entretien",
    "Fonction publique",
    "Edition, Journalisme",
    "Armée, sécurité",
    "Recherche",
    "Informatique et télécoms",
    "Commerce, distribution",
    "Audit, gestion",
    "Sport, loisirs – Tourisme",
    "Enseignement",
    "Culture - Artisanat d'art",
    "Électronique",
    "Mécanique",
    "Hôtellerie, restauration",
    "Logistique, transport",
    "Art, Design",
    "Santé",
    "Traduction - interprétariat",
    "Communication - Marketing - Pub",
    "Automobile",
    "BTP, architecture",
    "Environnement",
    "Droit, justice",
    "Verre, béton, céramique",
);
